### ISSUE TITLE
Official IDE already shows free SRAM memory in every compilation

### ISSUE THREAD

**Issue by q2dg** [maniacbug/MemoryFree#3]
So...I don't know if this library has still some reason to exist...hasn't it?

**Comment by per1234** [comment]
1) IDE shows SRAM used by global variables only, MemoryFree returns total SRAM usage(global and local variables).
2) Through dynamic memory allocation(malloc et al) even global variable memory usage can change while the program is running.
3) It is often useful to determine the free memory while the program is running instead of only at compile time. I use this library for detecting memory leaks.

**Comment by q2dg** [comment]
Aaah, ok, I see. Thanks a lot!
